-- ============================================================================
-- V012 - Jmix System Tables
-- Required tables for Jmix 2.x framework (Security, Audit, DataTools, FlowUI)
-- ============================================================================

-- Jmix Core: Configuration
CREATE TABLE IF NOT EXISTS SYS_CONFIG (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    NAME            VARCHAR(255)    NOT NULL,
    VALUE_          TEXT,
    CONSTRAINT PK_SYS_CONFIG PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SYS_CONFIG_NAME ON SYS_CONFIG(NAME);

-- Jmix Security: User
CREATE TABLE IF NOT EXISTS SEC_USER (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    UPDATED_TS      TIMESTAMPTZ,
    UPDATED_BY      VARCHAR(100),
    USERNAME_       VARCHAR(255)    NOT NULL,
    PASSWORD_       VARCHAR(255),
    FIRST_NAME_     VARCHAR(255),
    LAST_NAME_      VARCHAR(255),
    EMAIL_          VARCHAR(255),
    ACTIVE_         BOOLEAN         NOT NULL DEFAULT TRUE,
    TIME_ZONE_ID_   VARCHAR(255),
    CONSTRAINT PK_SEC_USER PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SEC_USER_USERNAME ON SEC_USER(USERNAME_);

-- Jmix Security: Role
CREATE TABLE IF NOT EXISTS SEC_ROLE (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    UPDATED_TS      TIMESTAMPTZ,
    UPDATED_BY      VARCHAR(100),
    NAME_           VARCHAR(255)    NOT NULL,
    CODE_           VARCHAR(255)    NOT NULL,
    DESCRIPTION_    TEXT,
    ROLE_TYPE_      INT             NOT NULL DEFAULT 0,
    CONSTRAINT PK_SEC_ROLE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SEC_ROLE_CODE ON SEC_ROLE(CODE_);

-- Jmix Security: User-Role Assignment
CREATE TABLE IF NOT EXISTS SEC_USER_ROLE (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    USER_ID         UUID            NOT NULL,
    ROLE_CODE_      VARCHAR(255)    NOT NULL,
    CONSTRAINT PK_SEC_USER_ROLE PRIMARY KEY (ID),
    CONSTRAINT FK_SEC_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SEC_USER(ID)
);
CREATE INDEX IF NOT EXISTS IDX_SEC_USER_ROLE_USER ON SEC_USER_ROLE(USER_ID);

-- Jmix Security: Resource Role Model
CREATE TABLE IF NOT EXISTS SEC_RESOURCE_ROLE_MODEL (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    UPDATED_TS      TIMESTAMPTZ,
    UPDATED_BY      VARCHAR(100),
    NAME_           VARCHAR(255)    NOT NULL,
    CODE_           VARCHAR(255)    NOT NULL,
    DESCRIPTION_    TEXT,
    SCOPES_         TEXT,
    CONSTRAINT PK_SEC_RESOURCE_ROLE_MODEL PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SEC_RESOURCE_ROLE_MODEL_CODE ON SEC_RESOURCE_ROLE_MODEL(CODE_);

-- Jmix Security: Row-Level Role Model
CREATE TABLE IF NOT EXISTS SEC_ROW_LEVEL_ROLE_MODEL (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    UPDATED_TS      TIMESTAMPTZ,
    UPDATED_BY      VARCHAR(100),
    NAME_           VARCHAR(255)    NOT NULL,
    CODE_           VARCHAR(255)    NOT NULL,
    DESCRIPTION_    TEXT,
    CONSTRAINT PK_SEC_ROW_LEVEL_ROLE_MODEL PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SEC_ROW_LEVEL_ROLE_MODEL_CODE ON SEC_ROW_LEVEL_ROLE_MODEL(CODE_);

-- Jmix Audit: Logged Entities
CREATE TABLE IF NOT EXISTS AUDIT_LOGGED_ENTITY (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    NAME_           VARCHAR(255)    NOT NULL,
    AUTO_           BOOLEAN         NOT NULL DEFAULT FALSE,
    CREATE_         BOOLEAN         NOT NULL DEFAULT FALSE,
    MODIFY_         BOOLEAN         NOT NULL DEFAULT FALSE,
    DELETE_         BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_AUDIT_LOGGED_ENTITY PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_AUDIT_LOGGED_ENTITY_NAME ON AUDIT_LOGGED_ENTITY(NAME_);

-- Jmix Audit: Logged Attributes
CREATE TABLE IF NOT EXISTS AUDIT_LOGGED_ATTR (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    ENTITY_ID       UUID            NOT NULL,
    NAME_           VARCHAR(255)    NOT NULL,
    CONSTRAINT PK_AUDIT_LOGGED_ATTR PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_LOGGED_ATTR_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES AUDIT_LOGGED_ENTITY(ID)
);

-- Jmix Audit: Entity Log
CREATE TABLE IF NOT EXISTS AUDIT_ENTITY_LOG (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    EVENT_TS        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    USERNAME_       VARCHAR(255),
    ENTITY_TYPE_    VARCHAR(255)    NOT NULL,
    ENTITY_ID_      VARCHAR(255),
    CHANGE_TYPE_    VARCHAR(1)      NOT NULL,
    CONSTRAINT PK_AUDIT_ENTITY_LOG PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_ENTITY_LOG_ENTITY ON AUDIT_ENTITY_LOG(ENTITY_TYPE_, ENTITY_ID_);

-- Jmix Audit: Entity Log Attribute Values
CREATE TABLE IF NOT EXISTS AUDIT_ENTITY_LOG_ATTR (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    LOG_ID          UUID            NOT NULL,
    NAME_           VARCHAR(255)    NOT NULL,
    VALUE_OLD_      TEXT,
    VALUE_NEW_      TEXT,
    CONSTRAINT PK_AUDIT_ENTITY_LOG_ATTR PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_ENTITY_LOG_ATTR_LOG FOREIGN KEY (LOG_ID) REFERENCES AUDIT_ENTITY_LOG(ID)
);

-- Jmix Audit: Session Log
CREATE TABLE IF NOT EXISTS AUDIT_SESSION_LOG (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    SESSION_ID_     VARCHAR(255),
    USERNAME_       VARCHAR(255),
    ENTERED_TS      TIMESTAMPTZ,
    EXITED_TS       TIMESTAMPTZ,
    CLIENT_INFO_    TEXT,
    CLIENT_TYPE_    VARCHAR(255),
    CONSTRAINT PK_AUDIT_SESSION_LOG PRIMARY KEY (ID)
);

-- Jmix File Storage
CREATE TABLE IF NOT EXISTS SYS_FILE (
    ID              UUID            NOT NULL DEFAULT gen_random_uuid(),
    VERSION         BIGINT          NOT NULL DEFAULT 0,
    CREATED_TS      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CREATED_BY      VARCHAR(100),
    UPDATED_TS      TIMESTAMPTZ,
    UPDATED_BY      VARCHAR(100),
    NAME_           VARCHAR(255)    NOT NULL,
    EXT_            VARCHAR(10),
    FILE_SIZE_      BIGINT,
    STORAGE_NAME_   VARCHAR(255),
    CONSTRAINT PK_SYS_FILE PRIMARY KEY (ID)
);

-- Insert default admin user (password: admin)
INSERT INTO SEC_USER (ID, USERNAME_, PASSWORD_, FIRST_NAME_, LAST_NAME_, ACTIVE_)
VALUES ('00000000-0000-0000-0000-000000000001', 'admin',
        '{bcrypt}$2a$10$LZ3bGPEhCIhK5kU3VxJ2.eJ0tNI8Y4Q3Y4Q3Y4Q3Y4Q3Y4Q3Y4Q3Y4',
        'System', 'Administrator', TRUE)
ON CONFLICT DO NOTHING;

-- Assign marketplace-admin role to default admin
INSERT INTO SEC_USER_ROLE (ID, USER_ID, ROLE_CODE_)
VALUES ('00000000-0000-0000-0000-000000000002',
        '00000000-0000-0000-0000-000000000001', 'marketplace-admin')
ON CONFLICT DO NOTHING;