# Jmix UI Configuration
jmix.ui.defaultScreenMode = TABBED
jmix.ui.maxFetchDepth = 3
jmix.ui.defaultFetchPlan = _base

# Entity inspector
jmix.entity-inspector.enabled = true

# File storage
jmix.localfs.enabled = true

# UI themes
jmix.ui.theme = halo

# Message bundle
jmix.ui.messageBundle = messages